language: node_js
os:
- linux
- osx
node_js:
- '8'
install:
- npm install -g esy@0.1.32
script:
- make bootstrap
- make ESY_RELEASE_TAG="$TRAVIS_TAG" platform-release
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CcWLCUQ57katTHXZlEALAXQAnEOf+WGy1sNvO8ebVqestkTqBLy26OBviZ9YLOprLyCkQWDeqc5cjpY/Itf6NbDiY1Zp5Sni2CydSfdO/AIshKfEv1CCGMgZxBWYU4+POoFmiTIZmEDsZSV6+i/SLoRqm5bGinQCO7CwFu9PCv4kPS3BA800xBBl1EuZrOcU1EdjjX5mNxyoRP5448EDXJJ/gSaCyj/2PjkardAKwtYHIvoW6FWT8niZ4l+bz5Rsgt+xKxs+3UMshFiIRwKAnA2iEslYE/Txa8kNTn9kDY+HheIsywKn+D+8FCY1s3zLbv6snrpuJqPEc4ylzbpoSxqH3fDlF2e+YVymrZBtO/wWiH4Pc7sQaMl0iYcKzOz2DAQ1hjfScyrak7hhfSwyiximqhZP+pu/QBYjS15C3vBfDoB7Mg4Hu5BszXB/QV1iBCtGs8e/5KKENzBvjUmTtm+zXXfhsBlsxiVEcmOGqbVTEgbZD5d0uXy76QFb6Qdj79WqwW5cMHOqyMC6lykaEHW9ApBZW2SaApzCJ19E3RgIvUbIjVOQHfYSgdgUVTgG8Y+6xxu/YVSwJGLhGa60uhhSeCyYhFSozYSdeJt0mrbl5xvTLKlweTwGDj+uiCEMLvDoBC07POXDHx+ejzeqw592+jF0FXO6cs2ptyJYnzo=
  file_glob: true
  file: _platformrelease/esy-solve-cudf-*-*.tgz
  on:
    repo: andreypopp/esy-solve-cudf
    tags: true
